import pytest

from services.ai_provider import (
    EvaluationResult,
    LLMConfigurationError,
    LLMProviderError,
    OpenAIProvider,
)
from services.autogen_orchestration import AutoGenProvider
from services import interview


class FakeCompletions:
    def __init__(self, content):
        self.content = content

    def create(self, **kwargs):
        class Message:
            def __init__(self, content):
                self.content = content

        class Choice:
            def __init__(self, content):
                self.message = Message(content)

        class Response:
            def __init__(self, content):
                self.choices = [Choice(content)]

        return Response(self.content)


class FakeClient:
    def __init__(self, content):
        self.chat = type("Chat", (), {"completions": FakeCompletions(content)})()


def valid_evaluation():
    return {
        "technical_correctness": 8,
        "relevance": 9,
        "completeness": 7,
        "clarity": 8,
        "strengths": ["Explains the trade-off"],
        "weaknesses": ["Needs a concrete metric"],
        "improvement_suggestions": ["Add a measured result"],
        "follow_up_required": True,
        "next_difficulty": "hard",
    }


def test_openai_provider_requires_api_key(monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    with pytest.raises(LLMConfigurationError):
        OpenAIProvider()


def test_openai_provider_generates_question_with_rag_context():
    provider = OpenAIProvider(api_key="test-key", client=FakeClient("Ask about caching."))
    question = provider.generate_question("Python Developer", "technical", "medium", [], "[Context 1]\nFastAPI")
    assert question == "Ask about caching."


def test_openai_provider_validates_structured_evaluation():
    import json

    provider = OpenAIProvider(
        api_key="test-key", client=FakeClient(json.dumps(valid_evaluation()))
    )
    result = provider.evaluate_answer("Python Developer", "What is FastAPI?", "A framework", "FastAPI", "medium")
    assert isinstance(result, EvaluationResult)
    assert result.score == 8
    assert result.next_difficulty == "hard"


def test_openai_provider_rejects_malformed_evaluation():
    provider = OpenAIProvider(api_key="test-key", client=FakeClient("not-json"))
    with pytest.raises(LLMProviderError):
        provider.evaluate_answer("Python Developer", "Question", "Answer", "Context", "medium")


def test_interview_service_retrieves_context_for_question_and_evaluation(monkeypatch):
    class FakeProvider:
        name = "fake"

        def generate_question(self, role, interview_type, difficulty, history, context):
            assert "candidate context" in context
            return "What did you build?"

        def evaluate_answer(self, role, question, answer, context, difficulty):
            assert "candidate context" in context
            return EvaluationResult(**valid_evaluation())

    monkeypatch.setattr(interview, "retrieve_context", lambda query, n_results: [{"text": "candidate context"}])
    service = interview.InterviewService()
    service.provider = FakeProvider()
    session = service.start("Python Developer", "technical", "medium", 2)
    question = service.next_question(session.session_id)
    result = service.evaluate(session.session_id, question["question"], "A detailed answer")
    assert result["technical_correctness"] == 8
    assert result["next_question_available"] is True


def test_autogen_provider_uses_interviewer_and_evaluator_roles():
    class FakeOrchestrator:
        def __init__(self):
            self.roles = []

        def run(self, role, task):
            self.roles.append(role)
            if role == "evaluator":
                import json

                return json.dumps(valid_evaluation())
            return "Generated by interviewer"

    orchestrator = FakeOrchestrator()
    provider = AutoGenProvider(api_key="test-key", orchestrator=orchestrator)
    assert provider.generate_question("Engineer", "technical", "medium", [], "context") == "Generated by interviewer"
    evaluation = provider.evaluate_answer("Engineer", "Question", "Answer", "context", "medium")
    assert isinstance(evaluation, EvaluationResult)
    assert orchestrator.roles == ["interviewer", "evaluator"]


def test_autogen_agents_have_distinct_role_prompts():
    from services.autogen_orchestration import AutoGenOrchestrator

    assert AutoGenOrchestrator.INTERVIEWER_SYSTEM_MESSAGE != AutoGenOrchestrator.EVALUATOR_SYSTEM_MESSAGE
    assert "exactly one interview question" in AutoGenOrchestrator.INTERVIEWER_SYSTEM_MESSAGE
    assert "valid JSON" in AutoGenOrchestrator.EVALUATOR_SYSTEM_MESSAGE


def test_autogen_orchestrator_builds_two_distinct_agents(monkeypatch):
    import sys
    import types

    class FakeAssistantAgent:
        def __init__(self, name, model_client, system_message):
            self.name = name
            self.model_client = model_client
            self.system_message = system_message

    class FakeSelectorGroupChat:
        def __init__(self, participants, **kwargs):
            self.participants = participants
            self.kwargs = kwargs

    class FakeModelClient:
        def __init__(self, **kwargs):
            self.kwargs = kwargs

    agents_module = types.ModuleType("autogen_agentchat.agents")
    agents_module.AssistantAgent = FakeAssistantAgent
    conditions_module = types.ModuleType("autogen_agentchat.conditions")
    conditions_module.MaxMessageTermination = lambda count: count
    teams_module = types.ModuleType("autogen_agentchat.teams")
    teams_module.SelectorGroupChat = FakeSelectorGroupChat
    models_module = types.ModuleType("autogen_ext.models.openai")
    models_module.OpenAIChatCompletionClient = FakeModelClient
    monkeypatch.setitem(sys.modules, "autogen_agentchat.agents", agents_module)
    monkeypatch.setitem(sys.modules, "autogen_agentchat.conditions", conditions_module)
    monkeypatch.setitem(sys.modules, "autogen_agentchat.teams", teams_module)
    monkeypatch.setitem(sys.modules, "autogen_ext.models.openai", models_module)

    from services.autogen_orchestration import AutoGenOrchestrator

    orchestrator = AutoGenOrchestrator("test-model", "test-key")
    assert orchestrator.workflow.participants == [
        orchestrator.interviewer_agent,
        orchestrator.evaluator_agent,
    ]
    assert orchestrator.interviewer_agent is not orchestrator.evaluator_agent
    assert orchestrator.interviewer_agent.name == "interviewer_agent"
    assert orchestrator.evaluator_agent.name == "evaluator_agent"


def test_autogen_provider_rejects_malformed_evaluation():
    class FakeOrchestrator:
        def run(self, role, task):
            assert role == "evaluator"
            return "not-json"

    provider = AutoGenProvider(api_key="test-key", orchestrator=FakeOrchestrator())
    with pytest.raises(LLMProviderError, match="malformed evaluation JSON"):
        provider.evaluate_answer("Engineer", "Question", "Answer", "context", "medium")


class FakeWorkflow:
    def __init__(self, interviewer_agent, evaluator_agent):
        self.interviewer_agent = interviewer_agent
        self.evaluator_agent = evaluator_agent
        self.selected_agents = []

    async def run(self, task):
        selected_agent = (
            self.evaluator_agent if "Requested role: evaluator" in task else self.interviewer_agent
        )
        self.selected_agents.append(selected_agent)
        response = (
            "{\"technical_correctness\": 8, \"relevance\": 8, \"completeness\": 8, "
            "\"clarity\": 8, \"strengths\": [], \"weaknesses\": [], "
            "\"improvement_suggestions\": [], \"follow_up_required\": false, "
            "\"next_difficulty\": \"hard\"}"
            if selected_agent is self.evaluator_agent
            else "Ask about the candidate's caching design."
        )
        return type("Result", (), {"messages": [type("Message", (), {"content": response})()]})()


def fake_orchestrator():
    from services.autogen_orchestration import AutoGenOrchestrator

    orchestrator = object.__new__(AutoGenOrchestrator)
    orchestrator.interviewer_agent = object()
    orchestrator.evaluator_agent = object()
    orchestrator.workflow = FakeWorkflow(
        orchestrator.interviewer_agent,
        orchestrator.evaluator_agent,
    )
    return orchestrator


def test_autogen_orchestrator_routes_roles_and_returns_selected_response():
    import asyncio

    orchestrator = fake_orchestrator()
    interviewer_response = asyncio.run(orchestrator.run_async("interviewer", "Generate a question."))
    evaluator_response = asyncio.run(orchestrator.run_async("evaluator", "Evaluate an answer."))

    assert interviewer_response == "Ask about the candidate's caching design."
    assert "technical_correctness" in evaluator_response
    assert orchestrator.workflow.selected_agents == [
        orchestrator.interviewer_agent,
        orchestrator.evaluator_agent,
    ]


def test_autogen_orchestrator_rejects_unsupported_role():
    import asyncio

    with pytest.raises(LLMProviderError, match="Unsupported AutoGen role"):
        asyncio.run(fake_orchestrator().run_async("moderator", "Do something."))


def test_autogen_orchestrator_run_uses_sync_adapter_without_running_loop():
    orchestrator = fake_orchestrator()

    assert orchestrator.run("interviewer", "Generate a question.") == (
        "Ask about the candidate's caching design."
    )


def test_autogen_orchestrator_run_rejects_active_event_loop():
    import asyncio

    async def invoke_run():
        with pytest.raises(LLMProviderError, match="active event loop"):
            fake_orchestrator().run("interviewer", "Generate a question.")

    asyncio.run(invoke_run())


def test_provider_selection_supports_local_openai_and_autogen(monkeypatch):
    from services.ai_provider import get_interview_provider

    monkeypatch.setenv("LLM_PROVIDER", "local")
    assert get_interview_provider().name == "local"

    monkeypatch.setenv("LLM_PROVIDER", "openai")
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    assert get_interview_provider().name == "openai"

    import services.autogen_orchestration as autogen_module

    class FakeAutoGenProvider:
        name = "autogen"

        def __init__(self):
            pass

    monkeypatch.setattr(autogen_module, "AutoGenProvider", FakeAutoGenProvider)
    monkeypatch.setenv("LLM_PROVIDER", "autogen")
    assert get_interview_provider().name == "autogen"
